@echo on
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE UTILS.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE AST.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE LABELS.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE LEXI.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE SYNT.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE TOKEN.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE OPTIMIZE.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE PREP.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE ASMGEN.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE CODGEN.C
C:\TC\TC\TCC.EXE -c -mc -IC:\TC\TC\INCLUDE CORTCOMP.C

C:\TC\TC\TCC.EXE -mc -eMYPROG.EXE -LC:\TC\TC\LIB CORTCOMP.OBJ CODGEN.OBJ ASMGEN.OBJ UTILS.OBJ AST.OBJ LABELS.OBJ LEXI.OBJ SYNT.OBJ TOKEN.OBJ OPTIMIZE.OBJ PREP.OBJ

echo Build complete.